apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: strimzi
    name: ${project.artifactId}
  name: ${project.artifactId}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: strimzi
        capability: bridge
        name: ${project.artifactId}
    spec:
      containers:
      - image: strimzi/${project.artifactId}:${project.version}
        name: ${project.artifactId}
        ports:
        - containerPort: 5672
          protocol: TCP
          name: amqp
        livenessProbe:
          tcpSocket:
            port: amqp
